#!/usr/bin/env ruby

STDERR.sync = STDOUT.sync = true

require 'observed/clockwork'

usage = 'observed-clockwork <observed.conf> <clock.rb>'

files = ARGV

abort usage unless files.size == 2

files = files.map do |file|
  if file.match(/^[\/.]/)
    file
  else
    "./#{file}"
  end
end

Observed::Clockwork::Handler.create_from_observed(
  :config_file => ARGV[0]
).register!

require files[1]

trap('INT') do
  puts "\rExiting"
  exit
end

Clockwork::run
